spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 5000 # The time to wait for connection thread from other microservices
            response-timeout: 20s # The time to wait for response from other microservices
  profiles:
    active:
      - "prod"

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Edge/ApiGateway Server"
    version: "1.0.0"

eureka:
  instance:
    preferredIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com:
      alienworkspace:
        cdr:
          cdredgegatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default: # name of the circuit breaker, if we want to have multiple circuit breaker configurations in our microservice
        # we can change this particular defaults one from default to any name so we can reference the name where we wish to use it
        slidingWindowSize: 10 # How many request to track before deciding to switch from closed to open
        permittedNumberOfCallsInHalfOpenState: 2 # How many requests to allow in half open state before switching to closed state
        failureRateThreshold: 50 # Percentage of failures to trigger circuit breaker
        waitDurationInOpenState: 10s # How long to wait before trying to switch to half-open state