spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  profiles:
    active:
      - "prod"

server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Edge/ApiGateway Server"
    version: "1.0.0"

eureka:
  instance:
    preferredIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com:
      alienworkspace:
        cdr:
          cdredgegatewayserver: DEBUG